export const ballControlConfig = Object.freeze({
  capture: Object.freeze({
    outfieldRadius: 28,
    goalkeeperRadius: 38,
    outfieldMaxHeight: 1.05,
    goalkeeperMaxHeight: 2.8,
    lastTouchSpeedBlock: 550,
    receivingSpeedSoftCap: 520,
    receivingSpeedHardCap: 900,
  }),
  firstTouch: Object.freeze({
    cleanScore: 0.72,
    cushionedScore: 0.5,
    heavyScore: 0.28,
    speedWeight: 0.38,
    angleWeight: 0.2,
    heightWeight: 0.18,
    movementWeight: 0.14,
    ratingWeight: 0.1,
    precisionBonus: 0.16,
    sprintPenalty: 0.18,
  }),
  dribble: Object.freeze({
    precisionLead: 7,
    normalLead: 12,
    sprintLead: 17,
    precisionLateral: 2.3,
    normalLateral: 3.8,
    sprintLateral: 5.2,
    precisionFollow: 28,
    normalFollow: 20,
    sprintFollow: 15,
  }),
  release: Object.freeze({
    passLock: 0.2,
    loftPassLock: 0.3,
    shotLock: 0.13,
    tackleLock: 0.18,
    kickoffLock: 0.8,
  }),
});
