export const cameraHudConfig = Object.freeze({
  camera: Object.freeze({
    baseZoom: 1.0,
    minZoom: 0.94,
    maxZoom: 1.035,
    speedZoomOutStart: 180,
    speedZoomOutRange: 620,
    maxSpeedZoomOut: 0.055,
    deadZoneX: 118,
    deadZoneY: 64,
    lookAheadMax: 74,
    lookAheadSpeed: 420,
    safeInsetX: 92,
    safeInsetTop: 66,
    safeInsetBottom: 112,
    followRate: 4.6,
    zoomRate: 2.8,
  }),
  three: Object.freeze({
    broadcast: Object.freeze({ height: 40, distance: 41, lowPowerHeight: 45, lowPowerDistance: 46, targetHeight: 0.7, zTracking: 0.06 }),
    tactical: Object.freeze({ height: 45, distance: 21, lowPowerHeight: 50, lowPowerDistance: 25, targetHeight: 0, zTracking: 0.04 }),
    close: Object.freeze({ offsetX: -9, height: 17, distance: 25, lowPowerHeight: 22, lowPowerDistance: 31, targetHeight: 1.2, zTracking: 0.12 }),
  }),
  radar: Object.freeze({
    width: 260,
    height: 140,
    plotPadding: 10,
    selectedRadius: 4.8,
    ballRadius: 3.8,
    playerRadius: 2.7,
  }),
});
