export const locomotionConfig = Object.freeze({
  controlled: Object.freeze({
    baseSpeed: 205,
    markingSpeed: 158,
    precisionSpeed: 132,
    sprintMultiplier: 1.42,
    accelerationResponse: 12,
    boostedAccelerationResponse: 16,
    markingResponse: 14,
    precisionResponse: 18,
    reversalResponse: 8,
    facingResponse: 18,
    precisionFacingResponse: 20,
    stopDamping: 0.0018,
    minimumMoveMagnitude: 0.03,
    sprintStaminaThreshold: 2,
    sprintDrainPerSecond: 11,
    movementDrainPerSecond: 1.1,
    precisionDrainPerSecond: 0.35,
    staminaRecoveryPerSecond: 5,
    precisionRecoveryPerSecond: 6.2,
    turnGripBase: 0.72,
    turnGripScale: 0.14,
  }),
  ai: Object.freeze({
    movementResponse: 8,
    arrivalRadius: 8,
    arrivalDamping: 0.7,
    facingVelocityThreshold: 4,
  }),
});
