#!/usr/bin/env bash
set -euo pipefail

mode=${1:-smoke}
case "$mode" in
  unit|smoke|flow|webgl-desktop|webgl-narrow) ;;
  *)
    cat >&2 <<'USAGE'
Usage: bash scripts/run-local-preflight.sh <mode>

Modes:
  unit             Run syntax, assets, simulation, presentation, and gameplay tests.
  smoke            Run unit tests, one desktop/narrow flow, and one desktop WebGL scenario.
  flow             Run all non-camera Playwright flows in desktop and narrow Chromium.
  webgl-desktop    Run a representative desktop Firefox software-WebGL scenario.
  webgl-narrow     Run a representative narrow Firefox software-WebGL scenario.

Run webgl-desktop and webgl-narrow as separate top-level commands in restricted chat containers.
USAGE
    exit 2
    ;;
esac

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

if [[ -f .local-playwright-env ]]; then
  # Generated by bootstrap-local-playwright.sh; contains only local paths.
  # shellcheck disable=SC1091
  source .local-playwright-env
fi

: "${PLAYWRIGHT_BROWSERS_PATH:?Set PLAYWRIGHT_BROWSERS_PATH or run bootstrap-local-playwright.sh first}"
command -v timeout >/dev/null || { echo "timeout is required for bounded local browser validation" >&2; exit 1; }

next_port=4300

run_unit() {
  npm run test:unit
}

run_flow_test() {
  local project=$1
  local file=$2
  local title=$3
  local port=$next_port
  next_port=$((next_port + 1))
  echo "[flow][$project][$port] $title"
  timeout --foreground 120s env \
    TONY_LOCAL_BROWSER=chromium \
    TONY_LOCAL_PORT="$port" \
    npx playwright test "$file" \
      --config=playwright.local.config.mjs \
      --project="$project" \
      --grep="$title"
}

run_webgl_project() {
  local project=$1
  local grep=${2:-}
  command -v xvfb-run >/dev/null || {
    echo "xvfb-run is required for local Firefox WebGL validation" >&2
    exit 1
  }

  local port=$next_port
  next_port=$((next_port + 1))
  local test_home test_tmp status
  test_home=$(mktemp -d "$repo_root/.local-firefox-home.XXXXXX")
  test_tmp=$(mktemp -d "$repo_root/.local-firefox-tmp.XXXXXX")
  trap 'rm -rf -- "$test_home" "$test_tmp"' RETURN

  local command=(
    npx playwright test tests/e2e/camera-hud.spec.mjs
    --config=playwright.local.config.mjs
    --project="$project"
  )
  [[ -z "$grep" ]] || command+=(--grep="$grep")

  echo "[webgl][$project][$port] ${grep:-all camera/HUD scenarios}"
  set +e
  timeout --foreground 360s xvfb-run -a env \
    HOME="$test_home" \
    TMPDIR="$test_tmp" \
    PLAYWRIGHT_BROWSERS_PATH="$PLAYWRIGHT_BROWSERS_PATH" \
    TONY_LOCAL_BROWSER=firefox \
    TONY_LOCAL_PORT="$port" \
    "${command[@]}"
  status=$?
  set -e
  rm -rf -- "$test_home" "$test_tmp"
  trap - RETURN
  return "$status"
}

flow_cases=(
  'tests/e2e/goal-presentation.spec.mjs|goal presentation yields native highlight and replay windows'
  'tests/e2e/goal-presentation.spec.mjs|score observer automatically presents an away goal after the highlight lead-in'
  'tests/e2e/match-flow-navigation.spec.js|main menu opens match setup as a distinct screen'
  'tests/e2e/match-flow-navigation.spec.js|pause can return directly to match setup'
  'tests/e2e/match-flow-navigation.spec.js|pause can return to the distinct main menu'
  'tests/e2e/match-intro.spec.mjs|match setup enters versus countdown kickoff and playing'
  'tests/e2e/match-intro.spec.mjs|gameplay remains locked until the presentation completes'
  'tests/e2e/post-match-hub.spec.mjs|post-match hub renders the final score, statistics, and three actions'
  'tests/e2e/post-match-hub.spec.mjs|play again keeps the selected match setup and starts immediately'
  'tests/e2e/post-match-hub.spec.mjs|post-match navigation returns to setup and the main menu'
)

case "$mode" in
  unit)
    run_unit
    ;;
  smoke)
    run_unit
    run_flow_test desktop-chromium tests/e2e/match-flow-navigation.spec.js "main menu opens match setup as a distinct screen"
    run_flow_test narrow-landscape tests/e2e/match-flow-navigation.spec.js "main menu opens match setup as a distinct screen"
    run_webgl_project desktop-chromium "low stamina exposes a restrained warning state"
    echo "Smoke passed. Run webgl-narrow separately when narrow WebGL evidence is required."
    ;;
  flow)
    for project in desktop-chromium narrow-landscape; do
      for entry in "${flow_cases[@]}"; do
        IFS='|' read -r file title <<<"$entry"
        run_flow_test "$project" "$file" "$title"
      done
    done
    ;;
  webgl-desktop)
    run_webgl_project desktop-chromium "low stamina exposes a restrained warning state"
    ;;
  webgl-narrow)
    run_webgl_project narrow-landscape "low stamina exposes a restrained warning state"
    ;;
esac
